# Generated by Django 5.1.4 on 2025-02-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technologies_used',
            field=models.CharField(default='none', help_text='Comma-separated list of technologies', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
